### ISSUE TITLE
Log warning

### ISSUE THREAD

**Issue by ribeiro-rodrigo** [globocom/enforcement-service#10]
Kopf is logging a warning message whenever a controller makes a status change. The message says "Paching failed with inconsistencies".
This warning does not interfere with the operation of the operator, but it would be good to understand the cause of this message and correct this problem.

![kopf-warnning](https://user-images.githubusercontent.com/28493895/97990213-5a3ef800-1dbe-11eb-83ea-61457562d9fe.png)

**Comment by matheusdaluz** [comment]
This problem was fixed in the new release of kopf [issue](https://github.com/nolar/kopf/issues/574)
